remote_theme: jekyll/minima

title: Running Routes
author: Thomas Turrell-Croft
description: A simple site using Minima theme

# Analytics
google_analytics: # Set your Google Analytics tracking ID here

minima:
  skin: auto
  nav_pages:
    - fell/bob-graham-round/index.md
    - fell/ramsay-round/index.md
    - fell/paddy-buckley-round/index.md
    - fell/wicklow-round/index.md
    - fell/allermuir-hill-race/index.md
  hide_site_feed_link: true
  social_links:
    - title: Running Routes repository
      icon: github
      url: "https://github.com/thomasturrell/running-routes/"

repository: thomasturrell/running-routes
edit_uri: edit/main/docs/

# Performance optimizations
sass:
  style: compressed

# Cache control
plugins:
  - jekyll-sitemap
  - jekyll-feed

#baseurl: "/running-routes"
#url: "https://thomasturrell.github.io"
